# -*- coding: utf-8 -*-
"""Web_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcCzQwZAfNFk9oidGw8GO6Zd7y1nTUdL

# BUILDING WEBSITE-AGENT IN 5 SIMPLE STEPS

### STEP 1: SETTING UP THE ENVIRONMENT
"""

# STEP 1: SET UP THE ENVIRONMENT

# STEP 1.1 INSTALL THE REQUIRED PACKAGES
!pip install langchain_community
!pip install -U duckduckgo-search

# STEP 1.2 IMPORT THE NECESSARY MODULES

# For loading the OpenAI API key safely into the colab environment
import os
from google.colab import userdata

# For Extracting the text from the URL
import requests
from bs4 import BeautifulSoup

# For creating the agent
from langchain.agents import initialize_agent, Tool, AgentType
from langchain.chat_models import ChatOpenAI

# STEP 1.3 LOAD THE OPEN AI API KEY
os.environ["OPENAI_API_KEY"] = userdata.get('openai')

"""### STEP 2: EXTRACTING TEXT FROM THE URL"""

# STEP 2: DEFINE A FUNCTION TO EXTRACT TEXT FROM URL
def extract_website_text(url):
  response = requests.get(url)
  soup = BeautifulSoup(response.text, "html.parser")
  return soup.get_text()

"""### STEP 3: CREATING THE WEBSITE Q AND A TOOL FOR THE AGENT"""

# STEP 3 CREATE THE TOOL


# STEP 3.1 DEFINE THE FUNCTION FOR PROCESSING THE USER INPUT
def website_qa_tool(url_and_question):
        url, question = url_and_question.split("|", 1)
        content = extract_website_text(url.strip())
        prompt = f"Answer this question using the content from the website:\n\n{question.strip()}\n\nContent:\n{content[:6000]}"
        llm = ChatOpenAI()
        return llm.predict(prompt)


# STEP 3.2 CREATE THE TOOL FOR THE AGENT USING THE FUNCTION CREATED

tool = Tool(
    name="WebsiteQnA",
    func=website_qa_tool,
    description="Input format: '<website URL> | <your question>'. Use this tool to ask questions about any website's content."

)

"""### STEP 4: INITIALIZING THE AGENT"""

# STEP 4: INITIALIZE THE AGENT

agent = initialize_agent(
    tools=[tool],
    llm=ChatOpenAI(),
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
    handle_parsing_errors=True
)

"""### STEP 5: RUNNING THE AGENT & CHECKING THE MAGIC!"""

# STEP 5: RUN THE AGENT
print(agent.run(" | ?"))